### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] find coordinates on x and y axis by using $img.x and $img.y
- [x] absolutely position the car
- [x] event listener on window to change offset of left and top box properties using elements.style.offset-position
- [x] setInterval to repeat this action every 16 milliseconds
